CL\Slack\Model\AttachmentConfirm:
    properties:
        title:
            type: string
        text:
            type: string
        okText:
            type: string
        dismissText:
            type: string